services:
  webserver:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - 661:80
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: visitantes
      MYSQL_USER: db_user
      MYSQL_PASSWORD: '123'
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "662:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: '123'
